### ISSUE TITLE
Error when trying to open EddingtonGUI in windows

### ISSUE THREAD

**Issue by saroad2** [EddLabs/eddington-gui#79]
When running Eddington GUI, some users get the following error:

```
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "..\app\eddington_gui\_main_.py", line 2, in <module>
    from eddington_gui.app import main
  File "C:\Users\user2019\AppData\Local\Programs\EddingtonGUI\\app\eddington_gui\_init_.py", line 2, in <module>
    import matplotlib
  File "C:\Users\user2019\AppData\Local\Programs\EddingtonGUI\\app_packages\matplotlib\_init_.py", line 174, in <module>
    _check_versions()
  File "C:\Users\user2019\AppData\Local\Programs\EddingtonGUI\\app_packages\matplotlib\_init_.py", line 159, in _check_versions
    from . import ft2font
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by saroad2** [comment]
Fixed.
